version: '3.9'

services:
  volidam_postgres:
    image: postgres:16
    container_name: volidam_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - volidam_pg_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

  volidam:
    build: .
    container_name: volidam
    restart: always
    depends_on:
      - volidam_postgres
    env_file:
      - .env
    ports:
      - "${API_PORT}:4000"
    volumes:
      - volidam_uploads:/app/uploads
    command: sh -c "wait-port ${DB_HOST}:${DB_PORT} && npm run start:prod"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

volumes:
  volidam_pg_data:
  volidam_uploads:
